2184587/Controllers/Producto_CompraController.cs
using _2184587.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using Rotativa;

namespace _2184587.Controllers
{
    public class Producto_CompraController : Controller
    {
        // GET: Producto_Compra
        public ActionResult Index()
        {
            using (var db = new inventarioEntities1())
            {
                return View(db.producto_compra.ToList());
            }
        }

        public ActionResult ListarCompra()
        {
            using (var db = new inventarioEntities1())
            {
                return PartialView(db.compra.ToList());
            }
        }
        public ActionResult ListarProducto()
        {
            using (var db = new inventarioEntities1())
            {
                return PartialView(db.producto.ToList());
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(producto_compra producto_compra)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {

                using (var db = new inventarioEntities1())
                {
                    db.producto_compra.Add(producto_compra);
                   _ = db.SaveChanges();
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "error " + ex);
                return View();

            }
        }

        public ActionResult Details(int id)
        {
            using (var db = new inventarioEntities1())
            {
                var producto_compra = db.producto_compra.Find(id);
                return View(producto_compra);
            }
        }


        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventarioEntities1())
                {
                    producto producto_compraEdit = db.producto.Where(a => a.id == id).FirstOrDefault();
                    return View(producto_compraEdit);


                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(producto_compra producto_compraEdit)
        {
            try
            {
                using (var db = new inventarioEntities1())
                {
                    producto_compra oldproduct = db.producto_compra.Find(producto_compraEdit.id);
                    db.SaveChanges();

                    oldproduct.id_compra = producto_compraEdit.id_compra;
                    oldproduct.id_producto = producto_compraEdit.id_producto;
                    oldproduct.cantidad = producto_compraEdit.cantidad;



                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventarioEntities1())
                {
                    var producto_compra = db.producto_compra.Find(id);
                    db.producto_compra.Remove(producto_compra);
                    db.SaveChanges();
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }
        public ActionResult Reporte2()
        {
            var db = new inventarioEntities1();
            {
                var query = from tabProducto_Compra in db.producto_compra
                            join tabProducto in db.producto on tabProducto_Compra.id_producto equals tabProducto.id
                            select new Reporte2
                            {
                                id_compra = tabProducto_Compra.id_compra,
                                producto = tabProducto.nombre,
                                Cantidad = tabProducto_Compra.cantidad

                            };
                return View(query);
            }
        }
        public ActionResult ImprimirReporte()
        {
            return new ActionAsPdf("Reporte2") { FileName = "Reporte.pdf" };
        }

    }
}

2184587/Controllers/UsuarioController.cs
using _2184587.Models;
using System;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.Web.Security;


namespace _2184587.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        [Authorize]
        public ActionResult Index()
        {
            using (var db = new inventarioEntities1())
            {
                return View(db.usuario.ToList());
            }
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create(usuario usuario)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {

                using (var db = new inventarioEntities1())
                {
                    usuario.password = UsuarioController.HashSHA1(usuario.password);
                    db.usuario.Add(usuario);
                    _ = db.SaveChanges();
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }


        public static string HashSHA1(string value)
        {
            var sha1 = System.Security.Cryptography.SHA1.Create();
            var inputBytes = Encoding.ASCII.GetBytes(value);
            var hash = sha1.ComputeHash(inputBytes);

            var sb = new StringBuilder();
            for (var i = 0; i < hash.Length; i++)
            {

                sb.Append(hash[i].ToString("X2"));
            }
            return sb.ToString();
        }

        public ActionResult Details(int id)
        {
            using (var db = new inventarioEntities1())
            {
                var findUser = db.usuario.Find(id);
                return View(findUser);
            }
        }


        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventarioEntities1())
                {
                    usuario findUser = db.usuario.Where(a => a.id == id).FirstOrDefault();
                    return View(findUser);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(usuario editUser)
        {
            try
            {
                using (var db = new inventarioEntities1())
                {
                    usuario user = db.usuario.Find(editUser.id);

                    user.nombre = editUser.nombre;
                    user.apellido = editUser.apellido;
                    user.email = editUser.email;
                    user.fecha_nacimiento = editUser.fecha_nacimiento;
                    user.password = editUser.password;

                    db.SaveChanges();
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventarioEntities1())
                {
                    var findUser = db.usuario.Find(id);
                    db.usuario.Remove(findUser);
                    db.SaveChanges();
                    return RedirectToAction("index");
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }

        public ActionResult Login(string message = "")
        {
            ViewBag.Message = message;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string user, string password)
        {
            string passEncrip = UsuarioController.HashSHA1(password);
            using (var db = new inventarioEntities1())
            {
                var userLogin = db.usuario.FirstOrDefault(e => e.email == user && e.password == passEncrip);
                if(userLogin != null)
                {
                    FormsAuthentication.SetAuthCookie(userLogin.email, true);
                    Session["User"] = userLogin;
                    return RedirectToAction("index");
                }
                else
                {
                    return Login("Verifique sus datos");
                }
            }
        }
        
        [Authorize]

        public ActionResult CloseSession()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

2184587/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - ASP 2184587 ASP.NET</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Concert+One&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   <link rel="stylesheet" href="~/Content/Custom.css">

</head>

<body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("ASP 2184587", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Iniciar Sesion", "index", "Usuario")</li>
                        <li>@Html.ActionLink("Crear Usuario", "Create", "Usuario")</li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Usuario", "index", "Usuario")</li>
                            <li>@Html.ActionLink("Cliente", "index", "Cliente")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Funcionalidades <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Proveedor", "index", "Proveedor")</li>
                                    <li>@Html.ActionLink("Producto", "index", "Producto")</li>
                                    <li>@Html.ActionLink("Compra", "index", "Compra")</li>
                                    <li>@Html.ActionLink("Producto Compra", "index", "Producto_Compra")</li>

                                </ul>
                            </li>
                            <li>@Html.ActionLink("Carga Masiva", "uploadCSV", "Proveedor")</li>
                            <li>@Html.ActionLink("Reporte", "Reporte2", "Producto_Compra")</li>
                            <li>@Html.ActionLink("Cerrar Sesion", "CloseSession", "Usuario")</li>


                        }

                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <font color="white">
                    <p>&copy; @DateTime.Now.Year - ASP-2184587</p>
                    </font>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>